{% set name = "physiocurve" %}
{% set version = "2024.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3d048aa92f711c2a60569e43345b2eb72900c949f26ede525d926eb06dd3f16

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python >=3.9,<3.13
    - pip
    - poetry >=0.12
  run:
    - python >=3.9,<3.13
    - pandas >=2.0
    - numba >=0.59.1,<0.60
    - neurokit2 >=0.2.7,<0.3

test:
  imports:
    - physiocurve
    - physiocurve.pandas
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://framagit.org/jaj/physiocurve
  summary: Library to analyze biometric time series for Python
  description: |
    physiocurve is a library to analyze biometric time series such as ECG and
    pulse waves, often obtained from patient monitors.
  license: ISC
  license_file: LICENSE
  dev_url: https://framagit.org/jaj/physiocurve

extra:
  recipe-maintainers:
    - jaj42
