{% set name = "physiocurve" %}
{% set version = "2022.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24bc9f6a5ddbc52b9b776d0b52d44d465d54e0eca970dde6a9a67dc3c711b09d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python >=3.8,<3.11
    - pip
    - poetry >=0.12
  run:
    - python >=3.8,<3.11
    - pandas =1.4
    - numba =0.55.2
    - scipy =1.8.1
    - neurokit2 =0.2.0

test:
  imports:
    - physiocurve
    - physiocurve.pandas
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://framagit.org/jaj/physiocurve
  summary: Library to analyze biometric time series for Python
  description: |
    physiocurve is a library to analyze biometric time series such as ECG and
    pulse waves, often obtained from patient monitors.
  license: ISC
  license_file: LICENSE
  dev_url: https://framagit.org/jaj/physiocurve

extra:
  recipe-maintainers:
    - jaj42
